# Generated by Django 6.0.3 on 2026-03-11 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='predictor.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='predictor.team'),
            preserve_default=False,
        ),
    ]
