# Generated by Django 6.0.3 on 2026-03-11 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_fixture_away_team_fixture_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='kickoff_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
