# Generated by Django 6.0.3 on 2026-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_fixture_kickoff_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('played', 'Played')], default='upcoming', max_length=10),
        ),
    ]
