# Generated by Django 6.0.3 on 2026-03-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_fixture_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['kickoff_datetime']},
        ),
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('season', 'matchweek', 'home_team', 'away_team')},
        ),
    ]
